# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    name: Build and Use on ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: ["1.18", "1.19", "1.20", "1.21", "1.22", "1.23", "1.24"]
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.target }}

    - name: TestFunctions
      run: |
        go test -v -cover -failfast ./cmd/decorator/ 
        go test -v -cover -failfast ./decor/

    - name: Build
      run: |
        go install -a -work ./cmd/decorator/ 
        decorator
        decorator --help 
        cd ./example/usages/ && go build -toolexec decorator && ./usages && go clean && go clean -x
        cd ../..

    - name: TestExample
      run: |
        cd ./example/usages/ && go test -v -toolexec decorator -failfast
